-- RUN ALL OF THIS IN YOUR SUPABASE SQL EDITOR TO SET UP THE DATABASE

-- 1. POSTS TABLE
create table if not exists posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null, 
  user_name text, 
  song_name text not null,
  artist_name text not null,
  album_art_url text,
  preview_url text, -- Added preview URL support
  spotify_id text,
  rating integer check (rating >= 1 and rating <= 5),
  caption text
);

-- 2. USER FAVORITES (TOP 4)
create table if not exists user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null, 
  slot_number integer not null check (slot_number >= 0 and slot_number <= 3),
  track_name text not null,
  artist_name text not null,
  image_url text,
  unique (user_id, slot_number)
);

-- 3. COMMENTS
create table if not exists comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  user_name text not null,
  content text not null,
  parent_id bigint references comments(id) on delete cascade -- Threaded comments
);

-- 4. PLAYLISTS
create table if not exists playlists (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  cover_image_url text, 
  is_public boolean default true
);

-- 5. PLAYLIST ITEMS
create table if not exists playlist_items (
  id bigint generated by default as identity primary key,
  playlist_id bigint references playlists(id) on delete cascade not null,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  song_name text not null,
  artist_name text not null,
  album_art_url text,
  preview_url text,
  external_url text,
  position integer
);

-- 6. ENABLE REALTIME UPDATES
alter publication supabase_realtime add table posts;
alter publication supabase_realtime add table user_favorites;
alter publication supabase_realtime add table comments;
alter publication supabase_realtime add table playlists;
alter publication supabase_realtime add table playlist_items;

-- 7. (OPTIONAL) ROW LEVEL SECURITY
-- For development speed, we often disable RLS or allow all, 
-- but here is a basic policy to allow anyone to read/write for now:
alter table posts enable row level security;
create policy "Public Access" on posts for all using (true) with check (true);
-- You can verify this in Supabase Dashboard > Authentication > Policies if you have issues saving.

-- 8. FOLLOWS TABLE
create table if not exists follows (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  follower_id uuid references auth.users not null,
  following_id uuid references auth.users not null,
  unique(follower_id, following_id)
);

alter publication supabase_realtime add table follows;

-- 10. ADD UNIQUENESS CONSTRAINT TO POSTS
alter table posts add unique (user_id, song_name, artist_name);
