-- Create the table for posts
create table if not exists posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null, 
  user_name text, 
  song_name text not null,
  artist_name text not null,
  album_art_url text,
  spotify_id text,
  rating integer check (rating >= 1 and rating <= 5),
  caption text
);

-- Create the table for Top 4 favorites
create table if not exists user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null, 
  slot_number integer not null check (slot_number >= 0 and slot_number <= 3),
  track_name text not null,
  artist_name text not null,
  image_url text,
  unique (user_id, slot_number)
);

-- Create table for comments
create table if not exists comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  user_name text not null,
  content text not null,
  rating integer check (rating >= 0 and rating <= 5) -- Optional rating with comment
);

-- Turn on Realtime
alter publication supabase_realtime add table posts;
alter publication supabase_realtime add table user_favorites;
alter publication supabase_realtime add table comments;
