-- Enable Row Level Security (RLS) is generally recommended but we will keep it simple for now as per previous pattern

-- 1. Playlists Table
create table if not exists playlists (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  cover_image_url text, -- Can be one of the album covers from items
  is_public boolean default true
);

-- 2. Playlist Items (Songs within a playlist)
create table if not exists playlist_items (
  id bigint generated by default as identity primary key,
  playlist_id bigint references playlists(id) on delete cascade not null,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  song_name text not null,
  artist_name text not null,
  album_art_url text,
  preview_url text,
  external_url text,
  position integer -- for ordering
);

-- 3. Likes (Hearting a post)
create table if not exists post_likes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  post_id bigint references posts(id) on delete cascade not null,
  unique (user_id, post_id) -- prevent duplicate likes
);

-- 4. Follows (Social Graph)
create table if not exists follows (
  follower_id uuid references auth.users not null,
  following_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (follower_id, following_id)
);

-- 5. Enable Realtime for new tables
alter publication supabase_realtime add table playlists;
alter publication supabase_realtime add table playlist_items;
alter publication supabase_realtime add table post_likes;
