-- RUN THIS IN YOUR SUPABASE SQL EDITOR TO UPDATE THE SCHEMA

-- 1. Add preview_url to posts table if it doesn't exist
alter table posts add column if not exists preview_url text;

-- 2. Playlists Table
create table if not exists playlists (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  cover_image_url text, 
  is_public boolean default true
);

-- 3. Playlist Items
create table if not exists playlist_items (
  id bigint generated by default as identity primary key,
  playlist_id bigint references playlists(id) on delete cascade not null,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  song_name text not null,
  artist_name text not null,
  album_art_url text,
  preview_url text,
  external_url text,
  position integer
);

-- 4. Enable Realtime
alter publication supabase_realtime add table playlists;
alter publication supabase_realtime add table playlist_items;
